// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FindPolicyContext find policy context
//
// swagger:model findPolicyContext
type FindPolicyContext struct {

	// action
	Action string `json:"action,omitempty"`

	// object
	Object string `json:"object,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`
}

// Validate validates this find policy context
func (m *FindPolicyContext) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this find policy context based on context it is used
func (m *FindPolicyContext) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FindPolicyContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FindPolicyContext) UnmarshalBinary(b []byte) error {
	var res FindPolicyContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
