// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// CreateGroupPolicyOKCode is the HTTP code returned for type CreateGroupPolicyOK
const CreateGroupPolicyOKCode int = 200

/*CreateGroupPolicyOK evaluation result

swagger:response createGroupPolicyOK
*/
type CreateGroupPolicyOK struct {

	/*
	  In: Body
	*/
	Payload models.CreateGroupPolicyResponse `json:"body,omitempty"`
}

// NewCreateGroupPolicyOK creates CreateGroupPolicyOK with default headers values
func NewCreateGroupPolicyOK() *CreateGroupPolicyOK {

	return &CreateGroupPolicyOK{}
}

// WithPayload adds the payload to the create group policy o k response
func (o *CreateGroupPolicyOK) WithPayload(payload models.CreateGroupPolicyResponse) *CreateGroupPolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create group policy o k response
func (o *CreateGroupPolicyOK) SetPayload(payload models.CreateGroupPolicyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGroupPolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*CreateGroupPolicyDefault generic error response

swagger:response createGroupPolicyDefault
*/
type CreateGroupPolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateGroupPolicyDefault creates CreateGroupPolicyDefault with default headers values
func NewCreateGroupPolicyDefault(code int) *CreateGroupPolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateGroupPolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create group policy default response
func (o *CreateGroupPolicyDefault) WithStatusCode(code int) *CreateGroupPolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create group policy default response
func (o *CreateGroupPolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create group policy default response
func (o *CreateGroupPolicyDefault) WithPayload(payload *models.Error) *CreateGroupPolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create group policy default response
func (o *CreateGroupPolicyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGroupPolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
