// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// CreatePolicyOKCode is the HTTP code returned for type CreatePolicyOK
const CreatePolicyOKCode int = 200

/*CreatePolicyOK evaluation result

swagger:response createPolicyOK
*/
type CreatePolicyOK struct {

	/*
	  In: Body
	*/
	Payload models.CreatePolicyResponse `json:"body,omitempty"`
}

// NewCreatePolicyOK creates CreatePolicyOK with default headers values
func NewCreatePolicyOK() *CreatePolicyOK {

	return &CreatePolicyOK{}
}

// WithPayload adds the payload to the create policy o k response
func (o *CreatePolicyOK) WithPayload(payload models.CreatePolicyResponse) *CreatePolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create policy o k response
func (o *CreatePolicyOK) SetPayload(payload models.CreatePolicyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*CreatePolicyDefault generic error response

swagger:response createPolicyDefault
*/
type CreatePolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePolicyDefault creates CreatePolicyDefault with default headers values
func NewCreatePolicyDefault(code int) *CreatePolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &CreatePolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create policy default response
func (o *CreatePolicyDefault) WithStatusCode(code int) *CreatePolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create policy default response
func (o *CreatePolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create policy default response
func (o *CreatePolicyDefault) WithPayload(payload *models.Error) *CreatePolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create policy default response
func (o *CreatePolicyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
