// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// DeletePolicyOKCode is the HTTP code returned for type DeletePolicyOK
const DeletePolicyOKCode int = 200

/*DeletePolicyOK evaluation result

swagger:response deletePolicyOK
*/
type DeletePolicyOK struct {

	/*
	  In: Body
	*/
	Payload models.DeletePolicyResponse `json:"body,omitempty"`
}

// NewDeletePolicyOK creates DeletePolicyOK with default headers values
func NewDeletePolicyOK() *DeletePolicyOK {

	return &DeletePolicyOK{}
}

// WithPayload adds the payload to the delete policy o k response
func (o *DeletePolicyOK) WithPayload(payload models.DeletePolicyResponse) *DeletePolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete policy o k response
func (o *DeletePolicyOK) SetPayload(payload models.DeletePolicyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*DeletePolicyDefault generic error response

swagger:response deletePolicyDefault
*/
type DeletePolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePolicyDefault creates DeletePolicyDefault with default headers values
func NewDeletePolicyDefault(code int) *DeletePolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &DeletePolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete policy default response
func (o *DeletePolicyDefault) WithStatusCode(code int) *DeletePolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete policy default response
func (o *DeletePolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete policy default response
func (o *DeletePolicyDefault) WithPayload(payload *models.Error) *DeletePolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete policy default response
func (o *DeletePolicyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
