// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindGroupPolicyHandlerFunc turns a function with the right signature into a find group policy handler
type FindGroupPolicyHandlerFunc func(FindGroupPolicyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindGroupPolicyHandlerFunc) Handle(params FindGroupPolicyParams) middleware.Responder {
	return fn(params)
}

// FindGroupPolicyHandler interface for that can handle valid find group policy params
type FindGroupPolicyHandler interface {
	Handle(FindGroupPolicyParams) middleware.Responder
}

// NewFindGroupPolicy creates a new http.Handler for the find group policy operation
func NewFindGroupPolicy(ctx *middleware.Context, handler FindGroupPolicyHandler) *FindGroupPolicy {
	return &FindGroupPolicy{Context: ctx, Handler: handler}
}

/* FindGroupPolicy swagger:route GET /group policy grouping findGroupPolicy

FindGroupPolicy find group policy API

*/
type FindGroupPolicy struct {
	Context *middleware.Context
	Handler FindGroupPolicyHandler
}

func (o *FindGroupPolicy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindGroupPolicyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
