// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindPolicyHandlerFunc turns a function with the right signature into a find policy handler
type FindPolicyHandlerFunc func(FindPolicyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindPolicyHandlerFunc) Handle(params FindPolicyParams) middleware.Responder {
	return fn(params)
}

// FindPolicyHandler interface for that can handle valid find policy params
type FindPolicyHandler interface {
	Handle(FindPolicyParams) middleware.Responder
}

// NewFindPolicy creates a new http.Handler for the find policy operation
func NewFindPolicy(ctx *middleware.Context, handler FindPolicyHandler) *FindPolicy {
	return &FindPolicy{Context: ctx, Handler: handler}
}

/* FindPolicy swagger:route GET /policy policy findPolicy

FindPolicy find policy API

*/
type FindPolicy struct {
	Context *middleware.Context
	Handler FindPolicyHandler
}

func (o *FindPolicy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindPolicyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
