// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// PutGroupPolicyOKCode is the HTTP code returned for type PutGroupPolicyOK
const PutGroupPolicyOKCode int = 200

/*PutGroupPolicyOK evaluation result

swagger:response putGroupPolicyOK
*/
type PutGroupPolicyOK struct {

	/*
	  In: Body
	*/
	Payload models.PutGroupPolicyResponse `json:"body,omitempty"`
}

// NewPutGroupPolicyOK creates PutGroupPolicyOK with default headers values
func NewPutGroupPolicyOK() *PutGroupPolicyOK {

	return &PutGroupPolicyOK{}
}

// WithPayload adds the payload to the put group policy o k response
func (o *PutGroupPolicyOK) WithPayload(payload models.PutGroupPolicyResponse) *PutGroupPolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put group policy o k response
func (o *PutGroupPolicyOK) SetPayload(payload models.PutGroupPolicyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutGroupPolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*PutGroupPolicyDefault generic error response

swagger:response putGroupPolicyDefault
*/
type PutGroupPolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutGroupPolicyDefault creates PutGroupPolicyDefault with default headers values
func NewPutGroupPolicyDefault(code int) *PutGroupPolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &PutGroupPolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put group policy default response
func (o *PutGroupPolicyDefault) WithStatusCode(code int) *PutGroupPolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put group policy default response
func (o *PutGroupPolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put group policy default response
func (o *PutGroupPolicyDefault) WithPayload(payload *models.Error) *PutGroupPolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put group policy default response
func (o *PutGroupPolicyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutGroupPolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
