// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// PutPolicyOKCode is the HTTP code returned for type PutPolicyOK
const PutPolicyOKCode int = 200

/*PutPolicyOK evaluation result

swagger:response putPolicyOK
*/
type PutPolicyOK struct {

	/*
	  In: Body
	*/
	Payload models.PutPolicyResponse `json:"body,omitempty"`
}

// NewPutPolicyOK creates PutPolicyOK with default headers values
func NewPutPolicyOK() *PutPolicyOK {

	return &PutPolicyOK{}
}

// WithPayload adds the payload to the put policy o k response
func (o *PutPolicyOK) WithPayload(payload models.PutPolicyResponse) *PutPolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put policy o k response
func (o *PutPolicyOK) SetPayload(payload models.PutPolicyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutPolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*PutPolicyDefault generic error response

swagger:response putPolicyDefault
*/
type PutPolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutPolicyDefault creates PutPolicyDefault with default headers values
func NewPutPolicyDefault(code int) *PutPolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &PutPolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put policy default response
func (o *PutPolicyDefault) WithStatusCode(code int) *PutPolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put policy default response
func (o *PutPolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put policy default response
func (o *PutPolicyDefault) WithPayload(payload *models.Error) *PutPolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put policy default response
func (o *PutPolicyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutPolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
