// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutGroupPolicyHandlerFunc turns a function with the right signature into a put group policy handler
type PutGroupPolicyHandlerFunc func(PutGroupPolicyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutGroupPolicyHandlerFunc) Handle(params PutGroupPolicyParams) middleware.Responder {
	return fn(params)
}

// PutGroupPolicyHandler interface for that can handle valid put group policy params
type PutGroupPolicyHandler interface {
	Handle(PutGroupPolicyParams) middleware.Responder
}

// NewPutGroupPolicy creates a new http.Handler for the put group policy operation
func NewPutGroupPolicy(ctx *middleware.Context, handler PutGroupPolicyHandler) *PutGroupPolicy {
	return &PutGroupPolicy{Context: ctx, Handler: handler}
}

/* PutGroupPolicy swagger:route PUT /group policy grouping putGroupPolicy

PutGroupPolicy put group policy API

*/
type PutGroupPolicy struct {
	Context *middleware.Context
	Handler PutGroupPolicyHandler
}

func (o *PutGroupPolicy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutGroupPolicyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
